name: "Linux Release"

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: "go build -ldflags '-X main.version=${{ github.ref }}' -v ./..."

    - name: Test
      run: go test -v ./...
    
    - name: Get Tag Name
      id: get-tag-name
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Rename Binary
      run: "mv gitlab-group-crawler gitlab-group-crawler-${{ steps.get-tag-name.outputs.tag }}-linux-x86_64"

    - name: Create a Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.RELEASE_TOKEN }}"
        automatic_release_tag: "${{ steps.get-tag-name.outputs.tag }}"
        title: "Release ${{ steps.get-tag-name.outputs.tag }}"
        files: |
          gitlab-group-crawler-*
    

